# Generated by Django 3.1.3 on 2020-11-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soap_from_scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='scented_candles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('colour', models.CharField(max_length=255, verbose_name='Цвет')),
                ('Equipment', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('Overall_Overall', models.CharField(max_length=255, verbose_name='Габариты, см')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='natural_parfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('tas_notes', models.CharField(max_length=255, verbose_name='Базовые ноты')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('group', models.CharField(max_length=255, verbose_name='Группа')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('floor', models.CharField(max_length=255, verbose_name='Пол')),
                ('top_notes', models.CharField(max_length=255, verbose_name='Верхние ноты')),
                ('middle_notes', models.CharField(max_length=255, verbose_name='Средние ноты')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='base_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
