# Generated by Django 3.1.3 on 2020-11-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201112_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bacterial_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bar_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='care_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cream_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='scrub_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='souvenir_soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименования')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('the_brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('composition', models.CharField(max_length=255, verbose_name='Состав')),
                ('year_creation', models.CharField(max_length=255, verbose_name='Год создание')),
                ('porfumer', models.CharField(max_length=255, verbose_name='Порфюмер')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='scented_candles',
        ),
    ]
