# Generated by Django 3.1.3 on 2020-11-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201121_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base_soap',
        ),
    ]
