# Generated by Django 3.1.3 on 2020-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201201_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='specification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='object_id',
        ),
    ]
